"""new column age

Revision ID: 7cd88a096928
Revises: 62cb61841527
Create Date: 2023-12-13 15:48:46.140307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd88a096928'
down_revision = '62cb61841527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customerses', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customerses', 'age')
    # ### end Alembic commands ###
